# fly.toml app configuration file generated for np-ff on 2024-10-08T00:43:04+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'np-ff'
primary_region = 'ams'

[build]

[env]
  PORT = '3000'
  NODE_ENV = "production"
  SCOPES = 'read_assigned_fulfillment_orders,read_fulfillments,read_inventory,read_orders,read_products,write_assigned_fulfillment_orders,write_fulfillments,write_inventory,write_orders,write_products'
  SHOPIFY_API_KEY = 'c6b25c68afcae95124a8d30598fba535'
  SHOPIFY_APP_URL = 'https://np-ff.fly.dev'


[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
