# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9d1518f2d5806a8c957779058827e4d8"
name = "nova-poshta-fullfill"
handle = "nova-poshta-fullfill"
application_url = "https://poetry-kg-footwear-emacs.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "skat-checkout-test.myshopify.com"
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://poetry-kg-footwear-emacs.trycloudflare.com/auth/callback",
  "https://poetry-kg-footwear-emacs.trycloudflare.com/auth/shopify/callback",
  "https://poetry-kg-footwear-emacs.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
